### ISSUE TITLE
Cannot get handle to application on Windows 10 20H2

### ISSUE THREAD

**Issue by Aoi-hosizora** [valinet/WinCenterTitle#12]
I run this application on my `Windows 10 20H2`, following https://github.com/valinet/WinCenterTitle#installation. But I get a `Cannot get handle to application` error message.

I run this exe in an administrated cmd. And the permissions of the `WinCenterTitle` and `symbols` folders are also set as `Installation` said. And the `Command` key in xml file is also modified.

> Make sure folder owner is set to Administrators and that the Users group is added as well, with default permissions (Read & execute, List folder contents, and Read)

```
WinCenterTitle.exe /xml WinCenterTitle.xml
WinCenterTitle
==============
1. Hook Library Path: C:\Settings\WinCenterTitle\WinCenterTitleLibrary.dll
2. Hook Library Entry Point: 0x1dc0
3. LoadLibraryW address: -766050592
3. FreeLibrary address: -766064688
4. ERROR: Cannot get handle to application.
```

![image](https://user-images.githubusercontent.com/31433480/116032123-ad20aa80-a691-11eb-80ff-8bc136595d26.png)

**Comment by GanerCodes** [comment]
I'm getting this as well

**Comment by valinet** [comment]
> Register scheduled task which will enable the tweak at startup: run install.bat as administrator. This is one way of running the application using the SYSTEM account, which is required in order to be able to hook into DWM

It can't get a handle to the application unless run as the SYSTEM account. In the picture that you show, even though I don't understand the language, I presume you run it only as an administrator. Run it as SYSTEM user using "psexec.exe -i -s WinCenterTitle.exe" if you want to run it in a terminal and then see how it goes.

The XML is for you to help register it in Task Scheduler. It serves no purpose to the EXE, the app does not take any command line parameters.

**Comment by Aoi-hosizora** [comment]
@valinet Thx, it runs!!!

But the effect is quite strange, the title bar is not centered completely. Is v1.3.0.0 incompatible with 20H2?

![image](https://user-images.githubusercontent.com/31433480/132795954-ccb77b37-b79c-479e-b9ad-d8a52d05f5da.png)

**Comment by valinet** [comment]
Probably. Idk. I haven’t tested. If 1.3.0.0 does not work, try 1.2.0.0, they are the same, only the addresses changed to accommodate newer Windows builds.

**Comment by Aoi-hosizora** [comment]
@valinet Oh, 1.2.0.0 works well, thx :P

![image](https://user-images.githubusercontent.com/31433480/132826693-649fa83a-ec2f-4956-97a5-ee80a329cd77.png)

**Comment by Dhyfer1** [comment]
@Aoi-hosizora Can you help me with the installation process? I still don't understand it well :(
