### ISSUE TITLE
Failed to run with error code 0x100 after updating Windows to 19042.985

### ISSUE THREAD

**Issue by shinywong** [valinet/WinCenterTitle#13]
My OS is 20H2, WinCenterTitle run well until Windows updated to 19042.985 (KB5003173).

Now WinCenterTitle failed to run with error code 0x100. What is the cause of the issue?

**Comment by valinet** [comment]
I don't know exactly, try running it in a terminal and see what it outputs. Also, try the latest version if you upgraded to newer builds, maybe the updated version will help.

**Comment by shinywong** [comment]
Sorry, I've figured out the cause of the problem but forgot to comment.

The computer must be connected to the Internet at computer startup after installing a cumulative update.

After installing a cumulative update, "uDWM.pdb" file will be re-generated, and Internet is required to generate the file. If there is no Internet, the app will fail to run with error code 0x100.

My computer doesn't have an always connected Internet. That's the reason that caused the problem.

So the solution is: After installing a cumulative update, connect the computer to the Internet and run the scheduled task manually, then WinCenterTitle will work.

**Comment by valinet** [comment]
Yeah, true, whenever system files, specifically uDWM.dll, change, the offset information probably is not valid anymore so the app needs to regenerate it by downloading  the newest symbol files.
