### ISSUE TITLE
ERROR: Failed to run library entry point in application.

### ISSUE THREAD

**Issue by littlewhitecloud** [valinet/WinCenterTitle#24]
![image](https://github.com/valinet/WinCenterTitle/assets/71159641/51f2a22d-a87c-449b-8db1-75fe89c35a08)

**Comment by emre93a** [comment]
> ![image](https://user-images.githubusercontent.com/71159641/251675099-51f2a22d-a87c-449b-8db1-75fe89c35a08.png)

is this 22h2 ?

**Comment by littlewhitecloud** [comment]
yes
![image](https://github.com/valinet/WinCenterTitle/assets/71159641/c0b2a167-bf62-4238-98bb-e9aaf8017e12)

**Comment by emre93a** [comment]
> yes ![image](https://user-images.githubusercontent.com/71159641/251883942-c0b2a167-bf62-4238-98bb-e9aaf8017e12.png)

**use this for it
https://github.com/valinet/WinCenterTitle/releases/download/1.0.0.0/WinCenterTitleBin_1.0.0.0.zip**

**Comment by littlewhitecloud** [comment]
![image](https://github.com/valinet/WinCenterTitle/assets/71159641/0bcdea29-e62e-4a2c-9080-3de5928fa2e5)
![image](https://github.com/valinet/WinCenterTitle/assets/71159641/4c47860b-7e94-444c-92a3-246a1404c29f)
![image](https://github.com/valinet/WinCenterTitle/assets/71159641/a070db60-aad0-4017-ba2e-fe4c93b2c712)

Nothing happened, even rebooted

**Comment by littlewhitecloud** [comment]
Also 1.1.0.0 1.2.0.0 1.3.0.0

**Comment by emre93a** [comment]
> Also 1.1.0.0 1.2.0.0 1.3.0.0

So, are the visual packages installed on the computer?

**Comment by littlewhitecloud** [comment]
> > Also 1.1.0.0 1.2.0.0 1.3.0.0
> 
> So, are the visual packages installed on the computer?

what is visual packages？

**Comment by emre93a** [comment]
> > > Also 1.1.0.0 1.2.0.0 1.3.0.0
> > 
> > 
> > So, are the visual packages installed on the computer?
> 
> what is visual packages？

This ;
https://www.technopat.net/sosyal/indir/visual-c-redistributable-runtimes-hepsi-bir-arada.486/download

**Comment by littlewhitecloud** [comment]
Yes. I have them.

**Comment by emre93a** [comment]
> Yes. I have them.

**I'm using 22h2 too, but it works for me as well as version 1.1.0.0**

**Comment by littlewhitecloud** [comment]
That’s strange.
