### ISSUE TITLE
Just want to thank you by this awesome piece of code

### ISSUE THREAD

**Issue by Rosmaninho** [valinet/WinCenterTitle#5]
Hey, you can close this issue immediately.
Just wanted to say thank you!! This is really what I wanted to center the title of websites on Firefox titlebar. :)

**Comment by valinet** [comment]
No worries, sure, I am glad it serves you well. A lot more can be relatively easily achieved, like making titlebars glassy, like in Windows 7, one has to study the symbols a bit more, it is not impossible. The main issue is doing it in a manner that makes it easier to keep up with the upstream. Microsoft constantly updates DWM which will nevertheless break a particular approach to hacking a way to get whatever feature one wants. That’s the main issue, how to future proof the patch as much as possible, as it takes a lot of time and Windows releases are pretty often. I am doing this in the free time, and honestly, rarely have the patience to track down whatever modifications Microsoft may make. As I also told them in some Git thread, I just wish they open sourced DWM, big pretty absurd that third party compositors can’t really exist anyway. But at least give the community better ways to hook into DWM and do cool stuff.

Anyway, too long of an answer, thanks for the kind words, I hope the app makes you a bit more happy.
