### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by ygjsz** [valinet/WinCenterTitle#9]
Just a report about the question that I mentioned last time , you can close the issue immediately.
The gap was cauesd by AeroGlass from Big Muscle , when I disbale the AeroGlass , the gap disappeared.
So I used your code and set the value to -17
mov rax, -17
ret
And it looks prefectly.
Thanks a lot.
(Sorry for my bad English)
<img width="1019" alt="截屏2021-02-09 上午9 53 14" src="https://user-images.githubusercontent.com/45459216/107304957-ff075a80-6abc-11eb-8f3a-41d83f1edd67.png">

**Comment by valinet** [comment]
Hi

I am so glad that you got it working. That’s great news to hear.

I posted a link to this new issue as a comment in the old one, so people facing a similar problem also find out about the solution you have found.

It’s cool that it works with negative numbers too, really flexible.

Happy modding, I like your Windows look. Actually, if you don’t mind, can you upload some screenshots of File Explorer, and other things you find interesting? I think the look is identical to Windows 7, very good effort indeed. I like the stock like aesthetic, and Windows Aero looked the best.
